# Generated by Django 4.1.3 on 2022-11-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='', max_length=128)),
                ('modelo', models.CharField(default='', max_length=96)),
                ('kilometraje', models.CharField(default='', max_length=32)),
                ('precio', models.CharField(default='', max_length=32)),
            ],
        ),
    ]
