# Generated by Django 4.1.3 on 2022-12-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tareasExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.CharField(default='24-09-2022', max_length=256)),
                ('fechaEntrega', models.CharField(default='30-09-2022', max_length=256)),
                ('descripcion', models.CharField(default='', max_length=512)),
                ('estadoTarea', models.CharField(default='PROGRESO', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='usuariosFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default='', max_length=256)),
                ('contra', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
