# Generated by Django 4.1.3 on 2022-11-23 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyCurso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripion',
            new_name='descripcion',
        ),
    ]
