# Generated by Django 4.1.4 on 2022-12-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyCurso', '0003_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='idProductos',
            field=models.CharField(default='', max_length=256),
        ),
    ]
