# Generated by Django 4.1.4 on 2022-12-14 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyCurso', '0004_solicitud_idproductos'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 12, 13, 20, 22, 54, 559810)),
        ),
    ]
