# Generated by Django 4.1.4 on 2022-12-14 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyCurso', '0005_solicitud_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cliente',
            field=models.CharField(default='Cliente', max_length=128),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 12, 13, 20, 28, 24, 381758)),
        ),
    ]
