# Generated by Django 4.1.4 on 2022-12-14 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyCurso', '0006_solicitud_cliente_alter_solicitud_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='codigoSolicitud',
            field=models.CharField(default='SOL-0000', max_length=128),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 12, 13, 20, 34, 33, 930188)),
        ),
    ]
